services:
  app:
    build: .
    container_name: mt5_restful_api
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
    networks:
      - homelabs

networks:
  homelabs:
    driver: bridge